<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <Version>1.0.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Model" Version="10.9.9">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Controller" Version="10.9.9">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\downloaders.html" />
    <EmbeddedResource Include="Web\downloaders.js" />
  </ItemGroup>
  <ItemGroup>
    <None Update="seedr_helper.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="torbox_helper.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="meta.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="jellyfin_scraper.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
