<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <Version>1.3.2.0</Version>
    <AssemblyVersion>1.3.2.0</AssemblyVersion>
    <FileVersion>1.3.2.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Model" Version="10.9.9">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Controller" Version="10.9.9">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="TMDbLib" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\downloaders.html" />
    <EmbeddedResource Include="Web\downloaders.js" />
    <EmbeddedResource Include="Web\jellyfetch-inject.js" />
  </ItemGroup>
</Project>
